# GNU Make project makefile autogenerated by Premake
ifndef config
  config=debug_arm
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),debug_arm)
  CC         = /usr/bin/arm-linux-gnueabihf-gcc
  CXX        = /usr/bin/arm-linux-gnueabihf-g++
  AR         = /usr/bin/arm-linux-gnueabihf-ar
  OBJDIR     = obj/arm/debug
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/Adafruit_TCS34725_Rpi
  DEFINES   += -DDEBUG
  INCLUDES  += -I/usr/arm-linux-gnueabihf/include
  CPPFLAGS  +=  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -std=c++11 -Wformat=2 -Wall -pipe -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L/usr/arm-linux-gnueabihf/lib
  LIBS      += -lrt -lwiringPi -lpthread 
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release_arm)
  CC         = /usr/bin/arm-linux-gnueabihf-gcc
  CXX        = /usr/bin/arm-linux-gnueabihf-g++
  AR         = /usr/bin/arm-linux-gnueabihf-ar
  OBJDIR     = obj/arm/release
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/Adafruit_TCS34725_Rpi
  DEFINES   += -DNDEBUG
  INCLUDES  += -I/usr/arm-linux-gnueabihf/include
  CPPFLAGS  +=  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -std=c++11 -Wformat=2 -Wall -pipe -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -L/usr/arm-linux-gnueabihf/lib
  LIBS      += -lpthread -lrt -lwiringPi
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),mocks_arm)
  CC         = /usr/bin/arm-linux-gnueabihf-gcc
  CXX        = /usr/bin/arm-linux-gnueabihf-g++
  AR         = /usr/bin/arm-linux-gnueabihf-ar
  OBJDIR     = obj/arm/mocks
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/Adafruit_TCS34725_Rpi
  DEFINES   += 
  INCLUDES  += -I/usr/arm-linux-gnueabihf/include
  CPPFLAGS  +=  $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -std=c++11 -Wformat=2 -Wall -pipe -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -L/usr/arm-linux-gnueabihf/lib
  LIBS      += -lpthread -lrt -lwiringPi
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug)
  OBJDIR     = obj/debug
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/Adafruit_TCS34725_Rpi
  DEFINES   += -DDEBUG
  INCLUDES  += -I/usr/arm-linux-gnueabihf/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -std=c++11 -Wformat=2 -Wall -pipe -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -L/usr/arm-linux-gnueabihf/lib
  LIBS      += -lpthread -lrt -lwiringPi
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release)
  OBJDIR     = obj/release
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/Adafruit_TCS34725_Rpi
  DEFINES   += -DNDEBUG
  INCLUDES  += -I/usr/arm-linux-gnueabihf/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -std=c++11 -Wformat=2 -Wall -pipe -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -L/usr/arm-linux-gnueabihf/lib
  LIBS      += -lpthread -lrt -lwiringPi
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),mocks)
  OBJDIR     = obj/mocks
  TARGETDIR  = .
  TARGET     = $(TARGETDIR)/Adafruit_TCS34725_Rpi
  DEFINES   += 
  INCLUDES  += -I/usr/arm-linux-gnueabihf/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -std=c++11 -Wformat=2 -Wall -pipe -fPIC
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -L/usr/arm-linux-gnueabihf/lib
  LIBS      += -lpthread -lrt -lwiringPi
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += 
  LINKCMD    = $(CXX) -o $(TARGET) $(OBJECTS) $(LDFLAGS) $(RESOURCES) $(ARCH) $(LIBS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/main.o \
	$(OBJDIR)/Adafruit_TCS34725.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking Adafruit_TCS34725_Rpi
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning Adafruit_TCS34725_Rpi
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/main.o: main.cc
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Adafruit_TCS34725.o: Adafruit_TCS34725.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
